IF OBJECT_ID('dbo.DISCONTINUED_TRIGGER', 'TR') IS NOT NULL
	DROP TRIGGER dbo.ORDER_TRIGGER
GO
CREATE TRIGGER [DISCONTINUED_TRIGGER] ON dbo.[GOOD]
AFTER UPDATE
AS 
DECLARE @GOOD_ID int
SET @GOOD_ID = (SELECT GOOD_ID FROM inserted)
BEGIN
	--UPDATE
	IF ((SELECT [STATUS] FROM inserted) = 'F') AND EXISTS (SELECT 1 FROM deleted)
		BEGIN
			SET NOCOUNT ON
			UPDATE dbo.[ORDER] SET [STATUS] = '3' WHERE GOOD_ID = @GOOD_ID AND [STATUS] = '1'
		END
END