IF OBJECT_ID('dbo.GOOD_TRIGGER', 'TR') IS NOT NULL
	DROP TRIGGER dbo.GOOD_TRIGGER
GO
CREATE TRIGGER GOOD_TRIGGER ON dbo.GOOD
AFTER INSERT, UPDATE
AS 
DECLARE @USER_ID int
SET @USER_ID = (SELECT [USER_ID] FROM inserted)
BEGIN
	IF EXISTS (SELECT 1 FROM inserted)
		BEGIN
			--SET NOCOUNT ON
			--新增商品時Account.Provide_count自動累加
			UPDATE dbo.ACCOUNT SET PROVIDE_COUNT = (PROVIDE_COUNT + 1) WHERE [USER_ID] = @USER_ID
		END
END