IF OBJECT_ID('dbo.ORDER_TRIGGER', 'TR') IS NOT NULL
	DROP TRIGGER dbo.ORDER_TRIGGER
GO
CREATE TRIGGER ORDER_TRIGGER ON dbo.[ORDER]
AFTER INSERT, UPDATE
AS 
DECLARE @GOOD_ID int
SET @GOOD_ID = (SELECT GOOD_ID FROM inserted)
DECLARE @AMOUNT int
SET @AMOUNT = (SELECT AMOUNT FROM inserted)
BEGIN
	--UPDATE
	IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted) AND UPDATE([STATUS])
		BEGIN
			SET NOCOUNT ON
			--新增提醒
			INSERT INTO dbo.NOTIFICATION(RECEIVE_ID, SEND_ID, CONTENT, GOOD_ID, URL, [TIME])
			SELECT i.[USER_ID] AS RECEIVE_ID, 
				   g.[USER_ID] AS SEND_ID, 
				   CASE i.[STATUS]
					 WHEN 2 THEN 
						REPLACE((SELECT NAME FROM dbo.CODE WHERE CODE_KIND = 'NTI' AND CODE_ID = '2'), 'XXX', '<b>'+g.TITLE+'</b>')
					 WHEN 3 THEN
						REPLACE((SELECT NAME FROM dbo.CODE WHERE CODE_KIND = 'NTI' AND CODE_ID = '3'), 'XXX', '<b>'+g.TITLE+'</b>')
					 ELSE ''
				   END AS CONTENT,
				   i.GOOD_ID AS GOOD_ID,
				   '/Store/GoodsDetail/' + CAST(i.GOOD_ID AS varchar(20)) AS URL,
				   GETDATE() AS [TIME]
			FROM inserted i
				LEFT JOIN dbo.GOOD g 
					ON i.GOOD_ID = g.GOOD_ID
			--當贈與方拒絕時把數量加回去
			IF (SELECT [STATUS] FROM inserted) = '3'
				UPDATE dbo.GOOD SET AMOUNT = AMOUNT + @AMOUNT WHERE GOOD_ID = @GOOD_ID
		END
	--INSERT
	ELSE IF NOT EXISTS (SELECT 1 FROM deleted) AND EXISTS (SELECT 1 FROM inserted)
		BEGIN
			SET NOCOUNT ON
			--新增提醒
			INSERT INTO dbo.NOTIFICATION(RECEIVE_ID, SEND_ID, CONTENT, GOOD_ID, URL, [TIME])
			SELECT g.[USER_ID] AS RECEIVE_ID, 
				   i.[USER_ID] AS SEND_ID, 
				   '<b>'+a.NAME+'</b>'+REPLACE((SELECT NAME FROM dbo.CODE WHERE CODE_KIND = 'NTI' AND CODE_ID = '1'), 'XXX', '<b>'+g.TITLE+'</b>') AS CONTENT,
				   i.GOOD_ID AS GOOD_ID,
				   '/Store/GoodsDetail/' + CAST(i.GOOD_ID AS varchar(20)) AS URL,
				   GETDATE() AS [TIME]
			FROM inserted i
				LEFT JOIN dbo.GOOD g 
					ON i.GOOD_ID = g.GOOD_ID
				LEFT JOIN dbo.ACCOUNT a
					ON i.USER_ID = a.USER_ID
			--更新商品數量
			UPDATE dbo.GOOD SET AMOUNT = AMOUNT - @AMOUNT WHERE GOOD_ID = @GOOD_ID
		END
END